//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialArtsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassTiming
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassTiming()
        {
            this.StudentAttendences = new HashSet<StudentAttendence>();
        }
    
        public int ClassID { get; set; }
        public string Class_Name { get; set; }
        public string Class_Day { get; set; }
        public Nullable<System.TimeSpan> Class_Time { get; set; }
        public string Class_Level { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAttendence> StudentAttendences { get; set; }
    }
}
