//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialArtsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parent
    {
        public int ParentID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string Mother_Name { get; set; }
        public string Father_Name { get; set; }
        public string Parent_Email { get; set; }
        public Nullable<bool> isStudent { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
