//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialArtsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFee
    {
        public int StudentFeeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> MembershipID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<System.DateTime> StudentFee_datetime { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual MembershipType MembershipType { get; set; }
        public virtual Student Student { get; set; }
        public virtual TestFee TestFee { get; set; }
    }
}
