//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MartialArtsWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendence
    {
        public int Attendence_ID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<System.DateTime> Student_datetime { get; set; }
        public Nullable<int> ClassID { get; set; }
    
        public virtual ClassTiming ClassTiming { get; set; }
        public virtual Student Student { get; set; }
    }
}
